# Generated by Django 3.0.7 on 2020-06-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weight',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
