# Generated by Django 3.0.7 on 2020-06-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200625_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_no',
            new_name='product_number',
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='from_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='relatedproduct',
            name='to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_product', to='product.Product'),
        ),
    ]
