# Generated by Django 3.0.7 on 2020-06-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200625_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hashtag', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Menu')),
            ],
        ),
    ]
