# Generated by Django 3.0.7 on 2020-07-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
