# Generated by Django 3.0.7 on 2020-06-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shpping',
            new_name='Shipping',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shopping',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='name',
        ),
    ]
