# Generated by Django 3.0.7 on 2020-06-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200625_1900'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shipping',
            table='shippings',
        ),
    ]
