# Generated by Django 3.0.7 on 2020-06-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200625_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_no',
            new_name='order_number',
        ),
    ]
