# Generated by Django 3.0.7 on 2020-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200625_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
