# Generated by Django 3.0.7 on 2020-06-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200625_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone_no', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'shipping_info',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShippingInfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShippingInfo'),
        ),
    ]
