# Generated by Django 3.0.7 on 2020-06-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shipping_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
    ]
