# Generated by Django 3.0.7 on 2020-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200630_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='phone_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
