# Generated by Django 3.0.7 on 2020-07-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200629_2105'),
        ('order', '0006_auto_20200630_1738'),
    ]

    operations = [
    ]
