# Generated by Django 3.0.7 on 2020-07-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200629_2105'),
        ('order', '0007_shipping_user'),
    ]

    operations = [
    ]
