# Generated by Django 3.0.7 on 2020-07-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200625_2106'),
        ('order', '0008_merge_20200703_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ShippingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('shipping_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShippingList')),
            ],
            options={
                'db_table': 'shipping_info',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShippingInfo'),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
